# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Client": "basic.ipynb"}

modules = ["pod/client.py"]

doc_url = "//integrators"

git_url = "https://gitlab.memri.io/memri/integrators/tree/master/"

def custom_doc_links(name): return None
