# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"DEFAULT_POD_ADDRESS": "pod.client.ipynb",
         "POD_VERSION": "pod.client.ipynb",
         "PodClient": "pod.client.ipynb"}

modules = ["pod/client.py"]

doc_url = """"

git_url = "https://gitlab.memri.io/memri/integrators/tree/master/"

def custom_doc_links(name): return None
