# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_file": "basic.ipynb",
         "read_json": "basic.ipynb",
         "write_json": "basic.ipynb",
         "Path.ls": "basic.ipynb",
         "Indexer": "indexers.indexer.ipynb",
         "ALL_EDGES": "itembase.ipynb",
         "UID_GEN": "itembase.ipynb",
         "generate_uid": "itembase.ipynb",
         "DB": "itembase.ipynb",
         "parse_base_item_json": "itembase.ipynb",
         "Edge": "itembase.ipynb",
         "ItemBase": "itembase.ipynb",
         "API_URL": "pod.client.ipynb",
         "PodClient": "pod.client.ipynb"}

modules = ["basic.py",
           "indexers/indexer.py",
           "itembase.py",
           "pod/client.py"]

doc_url = "//integrators"

git_url = "https://gitlab.memri.io/memri/integrators/tree/master/"

def custom_doc_links(name): return None
