# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/importers.Importer.ipynb (unless otherwise specified).

__all__ = ['ImporterBase']

# Cell
from ..data.schema import *
class ImporterBase(Importer):
    def __init__(self, importerClass=None, *args, **kwargs):
        super().__init__(*args, **kwargs)